### ISSUE TITLE
Group Name doesn't appear

### ISSUE THREAD

**Issue by DavidStodolsky** [MyTurn-OpenSource/pyturn#10]
Set up a session on Note 4.
Another Samsung phone loaded the site myturn.mobi, but the Group Name didn't appear.
Reload of site twice didn't resolve the problem.

**Comment by jcomeauictx** [comment]
myturn.mobi is a different app. pyturn requires the URL uwsgi-alpha.myturn.mobi.

but even if you get the URL right, the group refresh code isn't yet in place. that was precisely what I was working on before given the bot to work on. I'll get back on it today.

**Comment by jcomeauictx** [comment]
possible fix was just pushed to alpha. I'll need to change the default view to the group-select form for it to become apparent. otherwise a refresh of the page will still need to be made. I haven't yet updated uwsgi-alpha.myturn.mobi.

**Comment by jcomeauictx** [comment]
fixed and pushed to alpha, installed at uwsgi-alpha.myturn.mobi
